evaluation:
  epochs_between_evals: 2
model:
  learning_rate:
    initial_lr: 9.0
    name: polynomial
    warmup_epochs: 3
  loss:
    label_smoothing: 0.1
  model_params:
    rescale_inputs: true
  name: resnet
  optimizer:
    epsilon: 0
    lookahead: false
    momentum: 0.9
    name: lars
    weight_decay: 1.25e-05
model_dir: models
runtime:
  distribution_strategy: mirrored
  num_gpus: 1
train:
  callbacks:
    enable_checkpoint_and_export: true
  epochs: 39
  resume_checkpoint: true
train_dataset:
  batch_size: 256
  builder: records
  data_dir: None
  dtype: float32
  image_size: 224
  mean_subtract: false
  name: imagenet2012
  num_classes: 1000
  num_examples: 1281167
  one_hot: false
  split: train
  standardize: false
  use_per_replica_batch_size: true
validation_dataset:
  batch_size: 512
  builder: records
  data_dir: None
  dtype: float32
  image_size: 224
  mean_subtract: false
  name: imagenet2012
  num_classes: 1000
  num_examples: 50000
  one_hot: false
  split: validation
  standardize: false
  use_per_replica_batch_size: true
